# Generated by Django 3.1.2 on 2020-10-07 13:13

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name="Routes",
            fields=[
                ("id", models.FloatField(primary_key=True, serialize=False)),
                ("old_id", models.BigIntegerField()),
                ("sub_id", models.BigIntegerField()),
                ("source", models.FloatField()),
                ("target", models.FloatField()),
                ("dist", models.FloatField()),
                ("geom", django.contrib.gis.db.models.fields.MultiLineStringField(srid=4326)),
            ],
        ),
        migrations.CreateModel(
            name="Vertices",
            fields=[
                ("id", models.FloatField(primary_key=True, serialize=False)),
                ("val", models.IntegerField()),
                ("geom", django.contrib.gis.db.models.fields.MultiPointField(srid=4326)),
            ],
        ),
    ]
